### ISSUE TITLE
Question: how were the binaries built?

### ISSUE THREAD

**Issue by IanChok** [canad1an/cardano-stake-pool#1]
Hi, thanks for this awesome guide I'll definitely give it a try on my own Rasberry pi's! Quick question, I'm wondering how you built the binaries for cabal, cardano-node, and the cardano-cli?

**Comment by canad1an** [comment]
There is a group on telegram that is working toward supporting cardano on the Pi's. One of their developers built the binaries using modified versions of GHC. The README lists the steps to basically build the entire node yourself, then at the end, it overwrites the binaries that were built, with the latest stable versions. I have ordered a new RPi, and once I get it I will test options to reduce the setup time of a new pi.

**Comment by tensafefrogs** [comment]
I had this same question... It seems like a bad idea to install binaries for this from a random Github repo and I'd much prefer to build them myself if possible, but it does look like the GHC steps are pretty intensive.

Also not ideal to have to rely on you updating your repo whenever there are new updates to cardano-node released.

It would be great if you could share more details about where/how to get these binaries in the future in case things change.

**Comment by IanChokS** [comment]
I found [this](https://ci.zw3rk.com/build/719) as a pinned comment in the telegram group for the raspi developers. These are the updated binaries for cardano-node and cardano-cli for raspi, but so far I can't confirm if these are officially supported since there's no official documentation for raspi development

**Comment by canad1an** [comment]
Exactly @IanChokS  that is where I got the binaries.
And I agree, its not ideal to do this, but I don't have the exact steps to rebuild the binaries, and until I get that, i'll be hosting these binaries.

**Comment by tensafefrogs** [comment]
Thank you, even having a little more info on the provenance of this binaries is helpful. Please let us know when you are able to build from source!

Thanks for this guide, it's really great.
