### ISSUE TITLE
1.30.1 update is out

### ISSUE THREAD

**Issue by poonasor** [canad1an/cardano-stake-pool#3]
the 1.30.1 update has been out, any plans on updating the upgrading scripts?

**Comment by canad1an** [comment]
I should have the update soon.
When updates are released by IOHK they still take time to get ported to the aarch64 (Raspberry Pis) platform. Then I always upgrade first and test if they're successful. All that takes time.

**Comment by canad1an** [comment]
1.30.1 has been released.

**Comment by poonasor** [comment]
ahh okay, thanks for all your work
